baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hugo-blog-awesome"
[[params.socialIcons]]
name = "github"
url = "https://github.com/retsak"
[[params.socialIcons]]
name = "x"
url = "https://x.com/JosephDKaster"
[params]
  goToTop = true